apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-bosna
resources:
  - cronjob.yaml
images:
  - name: parlaparser-bosna
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-bosna
    newTag: 'f58ccf994b3d45f5b6b849e2f7d39a495721c85f'
